<?php

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function twig_lightbox_help($route_name, RouteMatchInterface $route_match)
{
    switch ($route_name) {
        case 'help.page.twig_lightbox':
            return t('
                        <h2>Lightbox in twig.</h2>
                        <p>This module wraps <img> with <a> via twig filter so that lightbox jquery plugin can be applied to it</p>
                    ');
    }
}
